apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fsw2n7e91-python
  janus-idp.io/tekton: fsw2n7e91-python
  backstage.io/kubernetes-id: fsw2n7e91-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fsw2n7e91-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
