apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fsw2n7e91-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fsw2n7e91-python 
  name: fsw2n7e91-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fsw2n7e91-python 
